# WhatATheme
markdown: kramdown

# URL of the Site
url: 'https://lowysole.github.io'
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Lowy Solé
# Description of the Site
description: My Personal Webpage
# URL of Image of the Site
site-image: assets/images/meta.jpg
# Keywords of the Site
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url: 

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: lowy.sole@gmail.com
twitter_username: lowysole
instagram_username: lowysole
linkedin_username: lowysole
github_username:  lowysole

# Google Analytics
google-analytics: 

# Name of the Author
author-name: Llorenç Solé Franquesa
# URL for the Image of the Author
author-image: ../../../../assets/images/lowy_profile.png
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/lowysole

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "project/:title"
permalink: "shaders/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
