# WhatATheme
markdown: kramdown

# URL of the Site
url: 'https://lowysole.github.io/'
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Lowy Solé
# Description of the Site
description: My Personal Webpage
# URL of Image of the Site
site-image: /lowysole.github.io/assets/images/meta.jpg
# Keywords of the Site
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://lh3.googleusercontent.com/pw/AM-JKLWmTVqU2Czyhxzv0d47XtPUIKpNQeumnAd8grdHOQEmf54bF1dPPhtztG0TgTcGT34918LTWN-jGSLnQMvnUgpDhDDCr-I4jdECwEPsDJhIA4Y65o02Neg0PHmns2xU39Oc5BnatPLU73HED3usbcCD=w1636-h920-no?authuser=0

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: lowy.sole@gmail.com
twitter_username: lowysole
instagram_username: lowysole
linkedin_username: lowysole
github_username:  lowysole

# Google Analytics
google-analytics: 

# Disqus
disqus-shortname: 

# Name of the Author
author-name: Llorenç Solé Franquesa
# URL for the Image of the Author
author-image: https://lh3.googleusercontent.com/nAe8uuFfHhJNSjSn_5-UhUDr_kYEV4S-ZzWCgrlx1pSFxIZB3h2uLbKhpuA8qMnqGkab6sQs_1V-UONNdt9Qazqwn9jaxT8938jaGq1suzU2M5zMVL1CjYp0hghQJoZwtoqfMYGjR5D9E5vSYHoDzCn5pz505bTSzPRDpJyqFwqoAeDBCzlVTD66rHpQLsT2CFO2VpJKu5HgmCDIrjuR3elMCucaJZmxtVhOBokKpW6CkSssGMbNon7JDM-cLffL9d9yV-3lCiYNz1FC75xxghYwu4y6l28oITkmGsul0qOWMjPyhuahY5wj3ACO5w67ipxHuEyvXDdjdYtdaEbxkvHQZo5_SPTLHtRzhGl6frT5RD99vyJ2VlrMSn7govLwLIwLJtBuAzsdXIFtkZpor7aVFU7SpUbCTLhQrZ1ZS4gCVwhHlrKQjgbpMgW7RRVMyp0tZgrfPkkylOC6fDzFxEyhGktDhwoCtVy7o0xGpnZ2UDZpjtBBldoMjxYh9Ia3KYEEVCvrsmVGR2LzSvcxxAGRtsVxmrMvC-X9qhMXSNNrSG5o945vmVJJUcEjaRXkICRKSsxagSkRKuldg6VCGV9zjNaAVbhSDpYyj0zjzQTKiPUKvmYBhANhFMghUu8AxH4rBhSMKliAfzrZYUZvx3L7cMVNqd4LVam9hHCYdMFw4E1NngCZMaNL5V7ChEajDPkvCK04k8W5h2jipBgeY0MM=s920-no?authuser=0
# 60 Words About the Author
author-about: "TODO"
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/lowysole

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'projects'
    values:
      layout: project
      post-image: ""
      description: ""
      tags:
        - ""

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
